### ISSUE TITLE
Implement Unfinish/Uncomplete feature

### ISSUE THREAD

**Issue by pyxyyy** [CS2103JAN2017-W09-B2/main#62]

**Comment by sharkey1314** [comment]
It's kinda of fixed already. I found several bugs in our program. Anyway the main issue is when we are 
@pyxyyy 
adding completed tasks to the completed list, there are duplicated tasks in there. So when i add meet you; finish 1; add meet you; finish 1. It throws this exception. This is because we do not allow for duplicated tasks in the list. However, I think we should allow for duplicated complete tasks (i might have add do homework multiple times). 
Question 1: Should we allow for duplication in the main list?
Question 2: Right now, I fixed the bug of duplication in completed list. Should we have duplicated tasks in completed list though?
The way I fix it was by adding a new attribute dateAdded which is definitely unique for all tasks
